version: 2

sources:
  - name: finance
    database: raw_data
    schema: finance
    tables:
      - name: raw_orders
        description: Raw orders data
        columns:
          - name: order_id
            description: Unique order identifier
          - name: customer_id
            description: Customer identifier
          - name: order_date
            description: Date when the order was placed
          - name: status
            description: Order status
          - name: amount
            description: Order amount
