name: 'finance'
version: '1.0.0'
config-version: 2

profile: 'finance'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  finance:
    staging:
      +materialized: view
    marts:
      +materialized: table
